### PR TITLE
🎨 Simplify use case by moving to nf-core/scrnaseq

### PR DESCRIPTION
**Pull request by Zethson**
- Moves to nf-core/rnaseq
- Adds more useful intro text on how to best use nextflow with lamin
- Functionizes the registration to make it more digestable and reusable

### CODE REVIEW

**Comment by sunnyosun** [comment]
There's a failed run on lamindata, could you clean it up and add a successful one?

Screenshot 2024-09-30 at 12 40 49

**Comment by sunnyosun** [comment]
Also this run misses outputs:
Screenshot 2024-09-30 at 12 41 55

**Comment by falexwolf** [comment]
This is great! It's very easy to understand & makes total sense now.

The only confusing thing is that you're using `ln.track()` within the registration (aka wrapper/glue) script.

I think it'd make more sense to simply create a `run` object and annotating it with inputs, outputs, and the correct timestamps.

`ln.track()` really is built for notebooks & scripts that serve the role of a data transformation. But here we're working with a mere registration/wrapper/glue script.

**Comment by falexwolf** [comment]
Hence, I refactored the script a bit. What's missing is adding the correct timestamps.

I'll look into the JSON field issue tomorrow. 505 lines of JSON 🤯 ...

**Comment by falexwolf** [comment]
Sorry for breaking things, @Zethson. I hope this refactor fixes it.

Will work on the JSON issue now.

**Comment by Zethson** [comment]
@falexwolf it didn't. Something in the script must still be wrong. I will look into it after breakfast while you're looking at the JSON stuff.

**Pull request merged**
